plugins {
    id 'java'
//    id 'com.roscopeco.jasm' version '0.7.0'
    id 'com.uselessmnemonic.jasm-plugin' version '1.0.0'
}

group = 'me.z7087'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    compileOnly project(":compileOnly")
}

//jasm.languageVersion = 17
//compileJasm.languageVersion = 17

java {
    targetCompatibility = sourceCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-Xlint:-options'
}

/*
-XX:+UnlockDiagnosticVMOptions
-XX:CompileCommand=print,me.z7087.Main::getMessage
-XX:CompileCommand=option,me.z7087.Main::getMessage,PrintCompilation
*/