plugins {
    id 'java'
}

group = 'me.z7087'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}


java {
    targetCompatibility = sourceCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-Xlint:-options'
}